import React, { useState, useEffect } from "react";
import { Text, View, StyleSheet, ScrollView } from "react-native";

export default function PrivacyPolicy({ navigation, route }) {
  return (
    <ScrollView>
    <View style={{margin: 10}}>
      <Text style={{fontSize: 20, fontWeight: 'bold', marginVertical: 5}}>Introduction</Text>
      <Text style={{fontSize: 15, marginVertical: 5, textAlign: 'justify'}}>
        We value your privacy and are committed to protecting your personal
        data. This privacy policy explains how our application handles your
        information.
      </Text>
      <Text style={{fontSize: 20, fontWeight: 'bold', marginVertical: 5}}>Information Collection and Use</Text>
      <Text style={{fontSize: 15, fontWeight: 'bold', marginVertical: 5}}>No Data Collection:</Text>
      <Text style={{fontSize: 15, marginVertical: 5, textAlign: 'justify'}}>
        Our application does not collect, transmit, or store any personal information or user data on external servers. All data generated by the application is stored locally on your device's SQLite database.
      </Text>
      <Text style={{fontSize: 20, fontWeight: 'bold', marginVertical: 5}}>Data Storage</Text>
      <Text style={{fontSize: 15, fontWeight: 'bold', marginVertical: 5}}>Local Storage:</Text>
      <Text style={{fontSize: 15, marginVertical: 5, textAlign: 'justify'}}>
        All the data you enter into the application is stored locally on your
        device. This means the information is not shared with us or any
        third-party services. Your data remains on your device unless you choose
        to share it.
      </Text>
      <Text style={{fontSize: 20, fontWeight: 'bold', marginVertical: 5}}>Security</Text>
      <Text style={{fontSize: 15, fontWeight: 'bold', marginVertical: 5}}>Data Security:</Text>
      <Text style={{fontSize: 15, marginVertical: 5, textAlign: 'justify'}}>
        We take reasonable measures to protect the data stored on your device.
        However, the security of your device and the data stored on it also
        depends on the measures you take. We recommend using security features
        like device passwords and encryption to safeguard your information.
      </Text>
      <Text style={{fontSize: 20, fontWeight: 'bold', marginVertical: 5}}>Third-Party Services</Text>
      <Text style={{fontSize: 15, fontWeight: 'bold', marginVertical: 5}}>No Third-Party Access:</Text>
      <Text style={{fontSize: 15, marginVertical: 5, textAlign: 'justify'}}>
        Since our application does not transmit any data to external servers, no
        third-party services have access to your data.
      </Text>
      <Text style={{fontSize: 20, fontWeight: 'bold', marginVertical: 5}}>User Rights</Text>
      <Text style={{fontSize: 15, fontWeight: 'bold', marginVertical: 5}}>Data Control:</Text>
      <Text style={{fontSize: 15, marginVertical: 5, textAlign: 'justify'}}>
        As the data is stored locally on your device, you have full control over
        it. You can delete the data at any time by uninstalling the application
        or using any data management features provided within the app.
      </Text>
      <Text style={{fontSize: 20, fontWeight: 'bold', marginVertical: 5}}>Changes to This Privacy Policy</Text>
      <Text style={{fontSize: 15, fontWeight: 'bold', marginVertical: 5}}>Policy Updates:</Text>
      <Text style={{fontSize: 15, marginVertical: 5, textAlign: 'justify'}}>
        We may update our privacy policy from time to time. Any changes will be
        reflected in the updated privacy policy, which will be available within
        the application.
      </Text>
      <Text style={{fontSize: 20, fontWeight: 'bold', marginVertical: 5}}>Contact Us</Text>
      <Text style={{fontSize: 15, fontWeight: 'bold', marginVertical: 5}}>Inquiries:</Text>
      <Text style={{fontSize: 15, marginTop: 5, textAlign: 'justify', marginBottom: 25}}>
        If you have any questions or concerns about this privacy policy, please
        contact us at dhriti.baruah20@gmail.com.
      </Text>
    </View>
    </ScrollView>
  );
}
